version: '3.8'

services:
  my-server:
    build:
      context: ./  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - movie-network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"  
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge
